import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:thesis_web/main_screens/mapping/mapping_management.dart';
import 'package:thesis_web/utils/lifecycle_observer.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Register a lifecycle observer ASAP so flutter/lifecycle messages have a listener
  WidgetsBinding.instance.addObserver(AppLifecycleObserver());
  // Also register a direct lifecycle channel handler early to avoid discarded messages
  SystemChannels.lifecycle.setMessageHandler((message) async {
    return null;
  });
  if (kIsWeb) {
    await Firebase.initializeApp(
        options: const FirebaseOptions(
            apiKey: "AIzaSyBtVHxTLVPvqmTG-OVAmoT5T3XH9QvwPec",
            authDomain: "security-tour-patrol-43d70.firebaseapp.com",
            projectId: "security-tour-patrol-43d70",
            storageBucket: "security-tour-patrol-43d70.firebasestorage.app",
            messagingSenderId: "201439742312",
            appId: "1:201439742312:web:7b06302a31b2cd8f3eaedd",
            measurementId: "G-B26LCNYS48"));
  } else {
    // For mobile, ensure you have firebase_options.dart generated by FlutterFire CLI
    // and use: await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    // The plain await Firebase.initializeApp(); might not be sufficient without further setup.
    await Firebase.initializeApp(); // This needs proper mobile setup if you intend to run on mobile
  }

  runApp(const SecurityGuardApp());
}

class SecurityGuardApp extends StatelessWidget {
  const SecurityGuardApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Security Guard App', // More general app title
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.light,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          brightness: Brightness.light,
        ),
        scaffoldBackgroundColor: Colors.white,
        // Remove cardTheme to avoid SDK/type mismatches; rely on cardColor and per-widget styles
        cardColor: Colors.grey.shade50,
        dividerColor: Colors.grey.shade300,
        appBarTheme: const AppBarTheme(centerTitle: false),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: Colors.grey.shade100,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          labelStyle: const TextStyle(color: Colors.black87),
        ),
      ),
      home: const MappingManagementScreen(),
    );
  }
}
